.config/nvim:
  type: git-repo
  url: https://github.com/awmath/neovim-config

.oh-my-zsh:
  type: git-repo
  url: https://github.com/ohmyzsh/ohmyzsh

.oh-my-zsh/custom/themes/powerlevel10k:
  type: git-repo
  url: https://github.com/romkatv/powerlevel10k

.oh-my-zsh/custom/plugins/fzf-tab:
  type: git-repo
  url: https://github.com/Aloxaf/fzf-tab

.fonts:
  type: archive
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip

.docker/cli-plugins/docker-compose:
  type: file
  url: https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64
  executable: true

.tmux/plugins/catpuccin:
  type: git-repo
  url: https://github.com/catppuccin/tmux
