name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: devcontainers/Containerfile.fedora
          push: true
          tags: |
            ghcr.io/awmath/devcontainer:latest
            ghcr.io/awmath/devcontainer:fedora
            ghcr.io/awmath/devcontainer:${{ github.sha }}
